### ISSUE TITLE
設定ファイルをTOMLにする

### ISSUE THREAD

**Issue by syobocat** [syobocat/plegosa#14]
PROS
- dotenvと比較し仕様が明確
- 階層構造を記述可能
- dotenvのini風記法とおおむね上方互換がある

CONS
- 破壊的変更

おそらく現行のdotenvとなら互換性があるので、0.1.3で採用しつつ.envファイルも読み込むように、0.2でdotenvを廃止　を計画

**Comment by syobocat** [comment]
配列が非互換ですね

**Comment by syobocat** [comment]
理想

```toml
[instance]
software = 'ソフトウェア名(例:Pleroma)'
url = 'インスタンスのURL(例:pleroma.social)'
token = 'アクセストークン(わからなければ空にしておくと生成してくれます、設定は手動)'

[timelines]
home = true
local = false
public = false

[filter]
case_sensitive = true
use_regex = false
include = [ "hoge", "fuga", "piyo" ]
exclude = [ "foo", "bar", "baz" ]
user_include = [ "hoge@foo", "fuga@bar", "piyo@baz" ]
user_exclude = [ "foo@hoge", "bar@fuga", "baz@piyo" ]

[logger.stdout]
enable = true

[logger.discord]
enable = false
webhook = 'DiscordのWebhook URL(LOGGERがDiscordの場合のみ)'
```
